services:
  tracking-service:
    build: .
    container_name: tracking_service
    ports:
      - "8087:8087"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: tracking_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
